"" General

let $VIMRUNTIME="~/.vim"

let vimplug_exists=expand('~/.vim/autoload/plug.vim')

if !filereadable(vimplug_exists)
  if !executable("curl")
    echoerr "You have to install curl or first install vim-plug yourself!"
    execute "q!"
  endif
  echo "Installing Vim-Plug..."
  echo ""
  silent !\curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  let g:not_finish_vimplug = "yes"

  autocmd VimEnter * PlugInstall
endif

"" Required
call plug#begin(expand('~/.vim/plugged'))

"" Color
Plug 'tomasr/molokai'

Plug 'chriskempson/base16-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'wellle/visual-split.vim'
Plug 'coderifous/textobj-word-column.vim'
Plug 'sjl/gundo.vim'
Plug 'airblade/vim-gitgutter'
Plug 'mhinz/vim-startify'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'tpope/vim-endwise'
Plug 'easymotion/vim-easymotion'

call plug#end()

set number	" Show line numbers
set nowrap	" Wrap lines
set linebreak	" Break lines at word (requires Wrap lines)
set showbreak=+++	" Wrap-broken line prefix
set textwidth=100	" Line wrap (number of cols)
set showmatch	" Highlight matching brace
 
set hlsearch	" Highlight all search results
set smartcase	" Enable smart-case search
set ignorecase	" Always case-insensitive
set incsearch	" Searches for strings incrementally
 
set autoindent	" Auto-indent new lines
set shiftwidth=2	" Number of auto-indent spaces
set smartindent	" Enable smart-indent
set smarttab	" Enable smart-tabs
set softtabstop=2	" Number of spaces per Tab
 
"" Advanced
set ruler	" Show row and column ruler information
set cmdheight=2	" Command line height
set tabstop=2
set expandtab
retab
set scrolloff=10

set whichwrap+=<,>,h,l,[,]

set undolevels=1000	" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

"" Directories for swp files
set nobackup
set noswapfile

set fileformats=unix,dos,mac

if exists('$SHELL')
    set shell=$SHELL
else
    set shell=/bin/sh
endif

"" Enable hidden buffers
set hidden

" session management
let g:session_directory = "~/.vim/session"
let g:session_autoload = "no"
let g:session_autosave = "no"
let g:session_command_aliases = 1

"" Colors
let g:molokai_original = 1
let g:rehash256 = 1
set background=light
colo cobalt

set cursorline
set colorcolumn=100
set cursorcolumn


"" Base16 Plugin
let base16colorspace=256  " Access colors present in 256 colorspace

"" Airline Plugin
let g:airline#extensions#tabline#enabled = 1

"" Filetype detection
autocmd BufNewFile,BufRead *.slim setlocal filetype=slim
